language: csharp
os:
  - osx
  - linux

sudo: required
dist: bionic

osx_image: xcode11.2

mono:
  - 5.12.0

dotnet:
  - 6.0.418
  - 7.0.405
  - 8.0.101

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh