//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Git")]
[assembly: AssemblyDescription("Cake Git AddIn")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("Cake.Git")]
[assembly: AssemblyVersion("0.18.0")]
[assembly: AssemblyFileVersion("0.18.0")]
[assembly: AssemblyInformationalVersion("0.18.0")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2018")]
[assembly: CLSCompliant(true)]

