name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-13, windows-2019, windows-2022]
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK (global.json)
        uses: actions/setup-dotnet@v4
        with:
            global-json-file: 'global.json'

      - name: Run Cake script
        uses: cake-build/cake-action@v2
        env:
          matrix-os: ${{ matrix.os }}
        with:
          target: GitHubActions
          cake-version: tool-manifest
