name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest, windows-2019, windows-2022]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core SDK (global.json)
        uses: actions/setup-dotnet@v1
        with:
            include-prerelease: 'true'

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        env:
          matrix-os: ${{ matrix.os }}
        with:
          target: GitHubActions
          cake-version: tool-manifest